pod "OpenSSL-Universal"

target 'Hekate Demo iOS' do
  target 'Hekate Tests iOS' do
        inherit! :search_paths
  end
end

target 'Hekate Demo macOS' do
  target 'Hekate Tests macOS' do
        inherit! :search_paths
  end  
end

target 'Hekate iOS' do
end

target 'Hekate macOS' do
end
